### ISSUE TITLE
Load model

### ISSUE THREAD

**Issue by harper-yuan** [tim-rohwedder/fixed-length-fingerprint-extractors#3]
I placed the model _best_model.pyt_ downloaded from Google's drive in notebooks/example-model and ran embedding_generation_tutorial.ipynb file may cause model loading errors:

![image](https://github.com/tim-rohwedder/fixed-length-fingerprint-extractors/assets/84079538/056d6c48-d9fe-4fac-8746-22a720bd3ed4)

Is the pre trained model wrong? Thank you for helping me answer the question @tim-rohwedder @dosorior

**Comment by tim-rohwedder** [comment]
![image](https://github.com/tim-rohwedder/fixed-length-fingerprint-extractors/assets/83403793/4e9d55ca-51c5-42bf-915b-0a6a7aaa2032)

In the code block at the beginning of the the notebook, you need to change the variable num_training_subjects to 8000. This was the number of subjects at training time of our model.
